"""增加APi agent 注册

Revision ID: 249fc431e059
Revises: 398427df95b4
Create Date: 2024-05-16 09:46:35.059994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '249fc431e059'
down_revision = '398427df95b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_agent_app',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('api_agent_id', postgresql.UUID(), nullable=False),
    sa.Column('app_id', postgresql.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='api_agent_app_pkey')
    )
    with op.batch_alter_table('api_agent_app', schema=None) as batch_op:
        batch_op.create_index('api_agent_id_app_id_idx', ['app_id', 'api_agent_id'], unique=False)

    op.create_table('api_agent_register',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('ai_agent_name', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='api_agent_register_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_agent_register')
    with op.batch_alter_table('api_agent_app', schema=None) as batch_op:
        batch_op.drop_index('api_agent_id_app_id_idx')

    op.drop_table('api_agent_app')
    # ### end Alembic commands ###
