"""增加消息过程数据表

Revision ID: 398427df95b4
Revises: 3c7cac9521c6
Create Date: 2024-05-16 03:01:56.955273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '398427df95b4'
down_revision = '3c7cac9521c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_info',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('message_id', postgresql.UUID(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('process', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='message_info_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_info')
    # ### end Alembic commands ###
