"""自定义agent增加初始问题

Revision ID: 596c5970fd67
Revises: a068e61100a5
Create Date: 2024-05-29 04:28:34.462773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596c5970fd67'
down_revision = 'a068e61100a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_agent_register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_agent_register', schema=None) as batch_op:
        batch_op.drop_column('collection')

    # ### end Alembic commands ###
