"""自定义agent增加初始问题

Revision ID: a068e61100a5
Revises: 249fc431e059
Create Date: 2024-05-27 06:30:45.652464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a068e61100a5'
down_revision = '249fc431e059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_agent_register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_questions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_agent_register', schema=None) as batch_op:
        batch_op.drop_column('suggested_questions')

    # ### end Alembic commands ###
