"""增加编排流

Revision ID: f95e9df55c54
Revises: 16830a790f0f
Create Date: 2024-03-30 08:50:42.201729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f95e9df55c54'
down_revision = '16830a790f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_flow',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='agent_flow_pkey')
    )
    op.create_table('agent_flow_third_party_api_config',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('sign', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=255), nullable=False),
    sa.Column('headers', sa.Text(), nullable=False),
    sa.Column('param_data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='agent_flow_api_config_pkey'),
    sa.UniqueConstraint('sign', name='agent_flow_api_config_sign_key')
    )
    op.create_table('agent_flow_version',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('agent_flow_id', postgresql.UUID(), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('flow_content', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='agent_flow_version_pkey')
    )
    with op.batch_alter_table('agent_flow_version', schema=None) as batch_op:
        batch_op.create_index('agent_flow_data_id_idx', ['agent_flow_id', 'version'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_flow_version', schema=None) as batch_op:
        batch_op.drop_index('agent_flow_data_id_idx')

    op.drop_table('agent_flow_version')
    op.drop_table('agent_flow_third_party_api_config')
    op.drop_table('agent_flow')
    # ### end Alembic commands ###
